# Generated by Django 5.2.4 on 2025-07-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='salary',
        ),
    ]
