# Generated by Django 5.2.4 on 2025-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquesolarprojectchecklist',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='uniquesolarprojectchecklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='uniquesolarprojectchecklist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='uniquesolarprojectchecklist',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='uniquesolarprojectchecklist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='uniquesolarprojectchecklist',
            name='project',
        ),
    ]
