# Generated by Django 5.2.4 on 2025-07-29 08:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_uniquesolarprojectchecklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquesolarproduct',
            options={'ordering': ['product_type', 'quantity', 'unit_price', 'line_total']},
        ),
        migrations.RemoveField(
            model_name='uniquesolarproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='uniquesolarproduct',
            name='specification',
        ),
        migrations.AddField(
            model_name='uniquesolarproduct',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='uniquesolarproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniquesolarproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='uniquesolarproduct',
            name='product_type',
            field=models.CharField(choices=[('solar_panel', 'Solar Panel'), ('inverter', 'Inverter'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uniquesolarprojectproduct',
            name='product_type',
            field=models.CharField(choices=[('solar_panel', 'Solar Panel'), ('inverter', 'Inverter'), ('others', 'Others')], max_length=50),
        ),
    ]
