# Generated by Django 5.2.4 on 2025-07-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_uniquesolarproduct_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
