# Generated by Django 5.2.4 on 2025-07-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_delete_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquesolarprojectimage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='uniquesolarprojectimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='uniquesolarprojectimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='uniquesolarprojectimage',
            name='order',
        ),
    ]
