# Generated by Django 5.2.4 on 2025-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_uniquesolarprojectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquesolarprojectimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='uniquesolarprojectimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the image (0-6, max 7 images per project)'),
        ),
        migrations.AlterUniqueTogether(
            name='uniquesolarprojectimage',
            unique_together={('project', 'order')},
        ),
    ]
