# Generated by Django 5.2.4 on 2025-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_alter_uniquesolarprojectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquesolarprojectproduct',
            name='specify_product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
