# Generated by Django 5.2.4 on 2025-07-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_uniquesolarprojectproduct_specify_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueSolarProjectChecklist',
            new_name='UniqueSolarChecklist',
        ),
    ]
