# Generated by Django 5.2.4 on 2025-07-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_rename_uniquesolarprojectchecklist_uniquesolarchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueSolarProjectChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Project.uniquesolarchecklist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='Project.uniquesolarproject')),
            ],
            options={
                'unique_together': {('project', 'checklist')},
            },
        ),
        migrations.DeleteModel(
            name='UniqueSolarProduct',
        ),
    ]
