# Generated by Django 5.2.4 on 2025-10-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_uniquesolarprojectchecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquesolarproject',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
