# Generated by Django 5.2.4 on 2025-10-09 23:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_uniquesolarproject_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarorratproject',
            name='advance_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='zarorratproject',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
