# Generated by Django 5.2.4 on 2025-10-29 10:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_zarorratproject_advance_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquesolarproject',
            name='installation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
