# Generated by Django 5.2.4 on 2025-08-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Tariq', 'Tariq'), ('Sajid', 'Sajid'), ('Wajid', 'Wajid')], max_length=255)),
                ('wage_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Wage', 'Wage')], default='Wage', max_length=20)),
                ('employee', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('total_paid', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('salary_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
