# Generated by Django 5.2.4 on 2025-08-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='image7',
        ),
    ]
