# Generated by Django 5.2.4 on 2025-08-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0002_remove_salary_image1_remove_salary_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='category',
            new_name='utilizer',
        ),
    ]
