# Generated by Django 5.2.4 on 2025-08-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0003_rename_category_salary_utilizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='utilizer',
        ),
    ]
