export const SampleSalaries = [
  {
    id: "1",
    srNo: 1,
    employeeName: "Ali Raza",
    wageType: "Monthly",
    month: "2025-01",
    salary: 34000,
    lastUpdated: "2025-01-15T10:30:00",
    designation: "Solar Engineer",
    datePaid: "2025-01-05",
    remarks: "Regular monthly salary payment for solar installation projects.",
    employeeId: "EMP-001",
  },
  {
    id: "2",
    srNo: 2,
    employeeName: "Sara Khan",
    wageType: "Daily",
    month: "2025-01",
    salary: 28000,
    lastUpdated: "2025-01-15T14:20:00",
    designation: "Sales Manager",
    datePaid: "2025-01-05",
    remarks: "Monthly salary with performance bonus included.",
    department: "Sales",
    employeeId: "EMP-002",
  },
  {
    id: "3",
    srNo: 3,
    date: "2025-01-15",
    employeeName: "Ahmed Hassan",
    designation: "Installation Technician",
    salary: 22000,
    datePaid: "2025-01-05",
    remarks: "Salary for solar panel installation and maintenance work.",
    department: "Operations",
    employeeId: "EMP-003",
  },
  {
    id: "4",
    srNo: 4,
    date: "2025-01-15",
    employeeName: "Fatima Sheikh",
    designation: "Project Manager",
    salary: 35000,
    datePaid: "2025-01-05",
    remarks: "Monthly salary for managing solar energy projects.",
    department: "Management",
    employeeId: "EMP-004",
  },
  {
    id: "5",
    srNo: 5,
    date: "2025-01-15",
    employeeName: "Muhammad Usman",
    designation: "Electrical Engineer",
    salary: 30000,
    datePaid: "2025-01-05",
    remarks: "Salary for electrical system design and implementation.",
    department: "Engineering",
    employeeId: "EMP-005",
  },
  {
    id: "6",
    srNo: 6,
    date: "2024-12-15",
    employeeName: "Aisha Malik",
    designation: "Customer Service Rep",
    salary: 18000,
    datePaid: "2024-12-05",
    remarks: "Monthly salary for customer support and service.",
    department: "Customer Service",
    employeeId: "EMP-006",
  },
  {
    id: "7",
    srNo: 7,
    date: "2024-12-15",
    employeeName: "Hassan Ali",
    designation: "Quality Inspector",
    salary: 25000,
    datePaid: "2024-12-05",
    remarks: "Salary for quality control and inspection services.",
    department: "Quality Assurance",
    employeeId: "EMP-007",
  },
  {
    id: "8",
    srNo: 8,
    date: "2024-12-15",
    employeeName: "Zainab Ahmed",
    designation: "Marketing Specialist",
    salary: 26000,
    datePaid: "2024-12-05",
    remarks: "Monthly salary for marketing and promotional activities.",
    department: "Marketing",
    employeeId: "EMP-008",
  },
];

export const designations = [
  "Solar Engineer",
  "Sales Manager",
  "Installation Technician",
  "Project Manager",
  "Electrical Engineer",
  "Customer Service Rep",
  "Quality Inspector",
  "Marketing Specialist",
  "Operations Manager",
  "Finance Manager",
];

export const departments = [
  "Engineering",
  "Sales",
  "Operations",
  "Management",
  "Customer Service",
  "Quality Assurance",
  "Marketing",
  "Finance",
  "Human Resources",
];

export const months = [
  "Jan-25",
  "Feb-25",
  "Mar-25",
  "Apr-25",
  "May-25",
  "Jun-25",
  "Jul-25",
  "Aug-25",
  "Sep-25",
  "Oct-25",
  "Nov-25",
  "Dec-25",
  "Jan-24",
  "Feb-24",
  "Mar-24",
  "Apr-24",
  "May-24",
  "Jun-24",
  "Jul-24",
  "Aug-24",
  "Sep-24",
  "Oct-24",
  "Nov-24",
  "Dec-24",
];
