export const SampleProducts = [
  {
    id: '1',
    srNo: 1,
    product: 'Solar Panel 400W Monocrystalline',
    cName: 'SunTech Solutions',
    purchPrice: 250,
    salePrice: 320,
    profit: 70,
    description: 'High-efficiency 400W monocrystalline solar panel with 25-year warranty. Perfect for residential and commercial installations with anti-reflective coating and robust aluminum frame.',
    category: 'Solar Panels',
    inStock: true,
    dateAdded: '2024-01-15',
    warranty: '25 years',
    efficiency: '22.1%',
    dimensions: '1956×992×35mm'
  },
  {
    id: '2',
    srNo: 2,
    product: 'Solar Inverter 5kW MPPT',
    cName: 'PowerTech Corp',
    purchPrice: 450,
    salePrice: 580,
    profit: 130,
    description: 'Advanced 5kW MPPT solar inverter with WiFi monitoring and mobile app integration for optimal energy management. Features comprehensive protection systems.',
    category: 'Inverters',
    inStock: true,
    dateAdded: '2024-01-20',
    warranty: '5 years',
    efficiency: '97.6%',
    dimensions: '375×220×110mm'
  },
  {
    id: '3',
    srNo: 3,
    product: 'Solar Battery 200Ah LiFePO4',
    cName: 'EcoEnergy Systems',
    purchPrice: 800,
    salePrice: 1050,
    profit: 250,
    description: 'Long-lasting 200Ah LiFePO4 battery with 6000+ cycle life. Ideal for off-grid solar systems and backup power with built-in BMS protection.',
    category: 'Batteries',
    inStock: false,
    dateAdded: '2024-01-25',
    warranty: '10 years',
    efficiency: '95%',
    dimensions: '522×240×219mm'
  },
  {
    id: '4',
    srNo: 4,
    product: 'Solar Charge Controller 60A',
    cName: 'SolarMax Industries',
    purchPrice: 120,
    salePrice: 165,
    profit: 45,
    description: 'Intelligent 60A MPPT charge controller with LCD display and multiple protection features for safe battery charging. Supports various battery types.',
    category: 'Controllers',
    inStock: true,
    dateAdded: '2024-02-01',
    warranty: '3 years',
    efficiency: '99.5%',
    dimensions: '186×125×60mm'
  },
  {
    id: '5',
    srNo: 5,
    product: 'Solar Mounting System Roof Kit',
    cName: 'MountPro Solutions',
    purchPrice: 85,
    salePrice: 125,
    profit: 40,
    description: 'Complete roof mounting system kit with aluminum rails and stainless steel hardware. Suitable for tile and metal roofs with easy installation.',
    category: 'Mounting',
    inStock: true,
    dateAdded: '2024-02-05',
    warranty: '20 years',
    efficiency: 'N/A',
    dimensions: 'Various sizes available'
  },
  {
    id: '6',
    srNo: 6,
    product: 'Solar Water Heater 200L',
    cName: 'AquaSolar Tech',
    purchPrice: 650,
    salePrice: 850,
    profit: 200,
    description: 'Efficient 200L solar water heater with evacuated tube collectors. Provides hot water for residential applications with frost protection.',
    category: 'Water Heaters',
    inStock: true,
    dateAdded: '2024-02-10',
    warranty: '8 years',
    efficiency: '85%',
    dimensions: '2100×1800×150mm'
  },
  {
    id: '7',
    srNo: 7,
    product: 'Solar Panel 550W Bifacial',
    cName: 'SunTech Solutions',
    purchPrice: 320,
    salePrice: 420,
    profit: 100,
    description: 'High-performance 550W bifacial solar panel that captures sunlight from both sides. Ideal for ground-mount installations with increased energy yield.',
    category: 'Solar Panels',
    inStock: true,
    dateAdded: '2024-02-15',
    warranty: '25 years',
    efficiency: '21.8%',
    dimensions: '2274×1134×35mm'
  },
  {
    id: '8',
    srNo: 8,
    product: 'Hybrid Inverter 10kW',
    cName: 'PowerTech Corp',
    purchPrice: 890,
    salePrice: 1150,
    profit: 260,
    description: 'Advanced 10kW hybrid inverter with battery backup capability. Features smart grid integration and energy management system.',
    category: 'Inverters',
    inStock: true,
    dateAdded: '2024-02-20',
    warranty: '5 years',
    efficiency: '97.8%',
    dimensions: '445×350×175mm'
  }
];