export const services = [
  { id: "ac", label: "AC Services" },
  { id: "fridge", label: "Fridge & Cooling" },
  { id: "electrician", label: "Electrician Services" },
  { id: "plumber", label: "Plumber Services" },
  { id: "handyman", label: "Handyman Services" },
  { id: "painter", label: "Painter Services" },
  { id: "carpenter", label: "Carpenter Services" },
  { id: "geyser", label: "Geyser Services" },
  { id: "ledtv", label: "LED TV Services" },
  { id: "stove", label: "Stove & Oven" },
  { id: "cctv", label: "CCTV Services" },
  { id: "washing", label: "Washing Machine" },
  { id: "sofa", label: "Sofa Cleaning" },
  { id: "plastic", label: "Plastic Tank Cleaning" },
  { id: "cement", label: "Cement Tank Cleaning" },
  { id: "solar", label: "Solar Panel Cleaning" },
  { id: "chair", label: "Chair Cleaning" },
  { id: "carpet", label: "Carpet Cleaning" },
  { id: "curtain", label: "Curtain Cleaning" },
  { id: "mattress", label: "Mattress Cleaning" },
];
