# Generated by Django 5.2.4 on 2025-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='utilizer',
            field=models.CharField(choices=[('Tariq', 'Tariq'), ('Sajid', 'Sajid'), ('Wajid', 'Wajid')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
